//-----------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
//        Copyright (c) Microsoft Corporation.  All rights reserved.
//        Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>
//-----------------------------------------------------------------------

/** Column names returned by the live semantic model on 2026-09-29. */
export const liveColumns = {
    modelFitSummary: [
        "[Sessions]",
        "[Logged Share]",
        "[Well-matched Share]",
        "[Over-specified Share]",
        "[Under-specified Share]",
        "[Coverage Notice]",
    ],
    modelUsage: ["[Model]", "[Cost Tier]", "[Tier Sort]", "[Sessions]", "[Usage Share]"],
    modelMatchByTool: ["[Activity]", "[Outcome]", "[Outcome Order]", "[Sessions]", "[Share]"],
    modelFitByTask: [
        "[Segment]",
        "[Main Model]",
        "[Main Reason]",
        "[Sessions]",
        "[Judged Sessions]",
        "[Well-matched Sessions]",
        "[Over-specified Sessions]",
        "[Under-specified Sessions]",
        "[Judged Share]",
        "[Well-matched Share]",
        "[Over-specified Share]",
        "[Under-specified Share]",
    ],
    modelFitByOrganization: [
        "[Segment]",
        "[Main Model]",
        "[Main Reason]",
        "[Sessions]",
        "[Judged Sessions]",
        "[Well-matched Sessions]",
        "[Over-specified Sessions]",
        "[Under-specified Sessions]",
        "[Judged Share]",
        "[Well-matched Share]",
        "[Over-specified Share]",
        "[Under-specified Share]",
    ],
    modelFitByPerson: [
        "[Segment]",
        "[Main Model]",
        "[Main Reason]",
        "[Sessions]",
        "[Judged Sessions]",
        "[Well-matched Sessions]",
        "[Over-specified Sessions]",
        "[Under-specified Sessions]",
        "[Judged Share]",
        "[Well-matched Share]",
        "[Over-specified Share]",
        "[Under-specified Share]",
    ],
    coworkFitByTask: ["[Task]", "[Grade]", "[Grade Order]", "[Share]", "[Sessions]", "[Task Sessions]"],
    coworkWorkShape: [
        "Chat + Agent Interactions (Audit Logs)[Work Weight Grade]",
        "Chat + Agent Interactions (Audit Logs)[Work Weight Grade Sort]",
        "Chat + Agent Interactions (Audit Logs)[Work Shape]",
        "Chat + Agent Interactions (Audit Logs)[Work Shape Sort]",
        "[Is Grand Total]",
        "[Is Group Total]",
        "[Sessions]",
        "[Decided By]",
        "[Could Have Used]",
        "[Share Of Work]",
        "[Source Items]",
        "[Source Types]",
    ],
    coworkFitPeople: [
        "Chat + Agent Org Data[Organization]",
        "Chat + Agent Interactions (Audit Logs)[Audit_UserId]",
        "[Is Grand Total]",
        "[Is Group Total]",
        "[People]",
        "[Sessions]",
        "[Strong]",
        "[Fair]",
        "[Worth A Look]",
        "[Flagged People]",
    ],
} as const;
