//-----------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
//        Copyright (c) Microsoft Corporation.  All rights reserved.
//        Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>
//-----------------------------------------------------------------------

/**
 * Column names the Consumption Central model returned when this page was
 * built. The whole-solution Azure queries came back empty, so theirs are the
 * names their DAX declares.
 */
export const liveColumns = {
    consumptionDates: ["[First Date]", "[Last Date]"],
    consumptionByProduct: ["[Product]", "[Product Sort]", "[Credits]", "[Cost]", "[Cost Basis]", "[Coverage]"],
    consumptionNotes: ["[Reporting Window]", "[Reporting Caveat]", "[Rates In Use]", "[Azure Currency]"],
    consumptionSources: ["[Cowork Rows]", "[Studio Rows]", "[Azure Rows]"],
    consumptionOptions: ["[Kind]", "[Value]", "[Sort]"],
    coworkCreditsSummary: [
        "[Credits Used]",
        "[Consuming Users]",
        "[Weekly Active Users]",
        "[Avg Credits Per User]",
        "[Allowance Used]",
        "[Users Over Limit]",
        "[Policies]",
        "[Total Cost]",
        "[Prepaid Cost]",
        "[PAYG Cost]",
        "[Blended Rate]",
        "[Avg Cost Per User]",
        "[Policy Headroom]",
        "[Billing Basis]",
        "[Period Label]",
    ],
    coworkWeekly: [
        "[Week Index]",
        "[Week Start]",
        "[Credits]",
        "[Active Users]",
        "[Prepaid Cost]",
        "[PAYG Cost]",
        "[Credits WoW]",
    ],
    coworkByGroup: [
        "Group By[Group]",
        "Org[DisplayName]",
        "[Is Grand Total]",
        "[Is Group Total]",
        "[Users]",
        "[Credits Used]",
        "[Allowance Used]",
        "[Prepaid Cost]",
        "[PAYG Cost]",
        "[Total Cost]",
        "[Policy]",
    ],
    studioCreditsSummary: [
        "[Credits Consumed]",
        "[Active Users]",
        "[Agents With Credits]",
        "[Avg Credits Per User]",
        "[Avg Agents Per User]",
        "[Total Cost]",
        "[Prepaid Cost]",
        "[PAYG Cost]",
        "[PAYG Share]",
        "[Effective Rate]",
        "[Avg Cost Per User]",
        "[Billing Period]",
        "[Period Label]",
        "[Concentration]",
        "[Snapshot Note]",
        "[Org Match Rate]",
        "[Org Filter Status]",
    ],
    studioDaily: ["[Usage Date]", "[Prepaid Credits]", "[PAYG Credits]", "[Credits]", "[Prepaid Cost]", "[PAYG Cost]"],
    studioBreakdown: ["[Breakdown]", "[Item]", "[Credits]", "[Cost]"],
    studioAgents: ["[Agent]", "[Credits Used]", "[Credit Share]", "[Billable Credits]", "[Estimated Cost]"],
    studioUsers: [
        "Group By[Group]",
        "Credit Consumption (User)[User Name]",
        "[Is Grand Total]",
        "[Is Group Total]",
        "[Credits Used]",
        "[Credit Share]",
        "[Billable Credits]",
        "[Estimated Cost]",
        "[Policy]",
    ],
    azureSource: ["[Solution Rows]", "[Solution Currencies]", "[Foundry Rows]", "[Foundry Currency]"],
    azureSolutionSummary: [
        "[Selected Cost]",
        "[Model Share]",
        "[Supporting Cost]",
        "[AI Requests]",
        "[Tagged Allocation]",
        "[Tokens M]",
        "[Speech Hours]",
        "[Document Pages]",
        "[Generated Images]",
        "[Cost Per 1M Tokens]",
        "[Spend Context]",
    ],
    azureSolutionDaily: ["[Usage Date]", "[Component]", "[Component Sort]", "[Cost]"],
    azureSolutionByService: ["[Item]", "[Cost]"],
    azureSolutionResources: ["[Resource]", "[Application]", "[Service]", "[Department Tag]", "[Cost]"],
    foundrySummary: [
        "[Cost]",
        "[Input Cost]",
        "[Output Cost]",
        "[Output Share]",
        "[Tokens M]",
        "[Cost Per 1M Tokens]",
        "[AI Requests]",
        "[Tokens Per Request]",
        "[Daily Run Rate]",
        "[Cost Per Month]",
        "[Days Observed]",
        "[PTU Verdict]",
    ],
    foundryDaily: ["[Usage Date]", "[Component]", "[Component Sort]", "[Cost]"],
    foundryByModel: ["[Item]", "[Cost]", "[Tokens M]"],
    foundryResources: ["[Resource]", "[Resource Group]", "[Model]", "[Department Tag]", "[Cost]", "[Tokens M]"],
} as const;
