EVALUATE
SUMMARIZECOLUMNS(
    ROLLUPADDISSUBTOTAL(
        ROLLUPGROUP(
            'Chat + Agent Org Data'[Organization],
            'Chat + Agent Interactions (Audit Logs)'[Audit_UserId]
        ),
        "IsTotal"
    ),
    "All Tasks", [AI Tasks],
    "Licensed Tasks", [Copilot AI Tasks],
    "Unlicensed Tasks", [Unlicensed AI Tasks],
    "Agent Tasks", [Agent AI Tasks],
    "Active Days", [Average Active Days Per User (Chat + Agents)]
)
ORDER BY [IsTotal] DESC, [All Tasks] DESC
